on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '2 * * * *'

jobs:
  ping_url:
    runs-on: ubuntu-latest
    name: Ping URL
    steps:
      - name: Check the URL
        id: ping
        uses: soul-wish/ping-url-javascript-action@v1.1
        with:
          url: 'https://google.com'
